missing fa translation
awcodes/filament-curator pull request #385
Opened 2023-12-16 20:15 UTC by mszabeh

2023-12-17 22:18 UTC, awcodes requested changes
Please update the view file too, to include the translation.

https://github.com/awcodes/filament-curator/blob/9db968c39c1a37b0c274bf85b51bfcafd6abbec6/resources/views/components/modals/curator-panel.blade.php#L60

2023-12-18 04:10 UTC, mszabeh commented
I added that here:
https://github.com/awcodes/filament-curator/pull/385/commits/59d68ea3165821af54114487916467765dc4780b

2023-12-18 13:56 UTC, awcodes approved these changes

2023-12-18 13:56 UTC, merged

2023-12-18 13:56 UTC, awcodes commented
Thanks. :)