Add Ability to Disable Curation Tab and Upload New Tab via Config
awcodes/filament-curator pull request #448
Opened 2024-02-25 02:03 UTC by onairmarc

This PR adds `tabs.display_curation` and `tabs.display_upload_new` to the `curator` config file with a default value of `true`.

Setting `tabs.display_curation` to `false` will hide the "Curation" tab on the Edit Media screen. This is useful for using Curator as a simple media library, but don't want to surface image manipulation features to your users. You could also use a class method to return `true` or `false` depending on the user's permissions.

Setting `tabs.display_upload_new` to `false` will hide the "Upload New" tab on the Edit Media screen. This is useful when you wish for users to not be able to override media files but upload new ones instead.

2024-02-27 21:12 UTC, onairmarc commented
@awcodes Would you mind taking a look at this, please?

2024-02-27 21:34 UTC, awcodes commented
I will when I get a chance. Pretty busy at the moment with work.

2024-02-28 20:45 UTC, awcodes requested changes
Please remove all formatting changes that are not part of the feature for the PR.

Thanks.

2024-02-28 20:51 UTC, onairmarc commented
> Please remove all formatting changes that are not part of the feature for the PR.
> 
> Thanks.

Ope! Sorry about that! I forgot my IDE was setup to do that. I'll do that this evening.

2024-02-29 03:20 UTC, onairmarc commented
@awcodes I believe I've reverted all the formatting changes. Please let me know if I missed anything and I'll happily correct them. Thanks!

2024-03-01 01:15 UTC, awcodes commented
This is so much better. 😁 I'll merge it tomorrow or Saturday. Thank you.

2024-03-01 01:44 UTC, onairmarc commented
Thank you!!

2024-03-02 21:14 UTC, awcodes approved these changes

2024-03-02 21:14 UTC, merged

2024-03-02 21:14 UTC, awcodes commented
Thanks. 🦒