Added Option to Set default layout from Config
awcodes/filament-curator pull request #457
Opened 2024-03-12 00:52 UTC by abbasmashaddy72

2024-03-12 23:19 UTC, awcodes commented
Can you do this so that it reads from the plugin as a modifier that defaults to the config? I'd like to be able to set it at that level with something like CuratorPlugin::defaultListView('table' || 'grid')

2024-03-13 06:01 UTC, abbasmashaddy72 commented
> Can you do this so that it reads from the plugin as a modifier that defaults to the config? I'd like to be able to set it at that level with something like CuratorPlugin::defaultListView('table' || 'grid')

We Can use Like:
`->defaultView('grid' || 'list')`

2024-03-15 08:11 UTC, abbasmashaddy72 commented
> Can you do this so that it reads from the plugin as a modifier that defaults to the config? I'd like to be able to set it at that level with something like CuratorPlugin::defaultListView('table' || 'grid')

This is Done Check and let me know if any changes

2024-03-15 14:13 UTC, awcodes commented
Thank you. I will look it over as soon as I get a chance. :)

2024-03-20 13:38 UTC, awcodes requested changes

2024-03-20 13:38 UTC, awcodes commented on config/curator.php
> +        'layout' => 'list',
Please default this to 'grid' since it is the current default.

2024-03-20 13:38 UTC, awcodes commented on src/CuratorPlugin.php
> +    public function defaultListView(): ?string
please rename to 'getDefaultListView' and update where appropriate.

2024-03-22 13:33 UTC, awcodes approved these changes

2024-03-22 13:33 UTC, merged